### ISSUE TITLE
Treemux doesn't appear to use configured nvim --listen path

### ISSUE THREAD

**Issue by l00sed** [kiyoon/nvim-tree-remote.nvim#1]
Hey @kiyoon, I'm a big Tmux + Neovim user and have been wanting some tools to be able to do what Treemux is doing. So, firstly, thanks for putting in the effort to release these tools for public use!

I've installed your Treemux plugin and I'm using `tmuxsend.vim` and `nvim-tree-remote.nvim` to try and get some this functionality setup together. I want to be able to open a file from Treemux into the `--listen`'ing nvim session, but there are a couple unexpected things happening.

Running `nvim --listen /tmp/nvim_tree_remote_socket` and then `prefix + Tab` opens up Treemux in a new pane. This all works as expected. The issue I'm finding is that hitting the return key opens up a _new_ Tmux pane instead of the one that's configured as the remote.

In my Neovim configs, I have `vim.g.nvim_tree_remote_socket_path = '/tmp/nvim_tree_remote_socket'`.

https://user-images.githubusercontent.com/23065167/210108921-4b7fe6a3-0d25-4199-9d4c-20fd42e5b66b.mp4

I'm also wanting to focus the pane where the file is opened when I open it from Treemux.

**Comment by kiyoon** [comment]
Hi, thank you for the feedback and sorry for the poor documentation that may have confused you.

The global variables for the `nvim-tree-remote.nvim` will be overridden by treemux, and you can access this value from the tmux buffer (`prefix + ]`) or (`prefix + =`) to find this command. So setting this value in your init file will have no effect. I thought I'd want to use treemux on many windows, so I don't want to have a fixed value for this. If you have an idea of how to access this value better, let me know!

And, focus is easy to fix. I'll make an update soon!

**Comment by kiyoon** [comment]
For debugging, you can print the values that are overridden.

```vim
:echo g:nvim_tree_remote_socket_path
:echo g:nvim_tree_remote_tmux_pane
```

You can use this shell script to send keys to a tmux pane. If you're not familiar with tmux scripting,  
```bash
tmux send-keys -t %0 Things to send
```

So you can basically send the socket path from the tree to the main pane easily. Here's the lua code.

```lua
os.execute("tmux send-keys -t '" ..  vim.g.nvim_tree_remote_tmux_pane .. "' '" .. vim.g.nvim_tree_remote_socket_path .. "'")
```

If you run this on the side tree, it will send the socket path to the main pane. With this, we can design a custom keymap to grab the `--listen` socket information when you need.

**Comment by kiyoon** [comment]
Hi, I just pushed an update for both this repo and Treemux.

Now the focus will go to the editor (customisable) and you can open to the main pane with `o` key. (if you use the provided init file).  
Can you check it out and let me know whether it's what you wanted to do?

**Comment by kiyoon** [comment]
For future reference, anyone who wants to use custom socket path should follow "Advanced configuration" section in `README.md`, as Treemux will override the global variables. Closing as completed.

**Comment by kiyoon** [comment]
Hi, the behaviour of treemux has changed and it will no longer override the `g:nvim_tree_remote_socket_path`. Instead, if the value is unset, it will just open the nvim running within the same tmux window at the default --listen path.

So, now you can just run `nvim` without explicitly setting the `--listen` and treemux will open the file on that neovim if you haven't set `g:nvim_tree_remote_socket_path` explicitly.
